### ISSUE TITLE
scanner matching

### ISSUE THREAD

**Issue by lillyfwang** [alexandramedway/plt#2] opened 2015-10-19 05:07 UTC
scanner is matching the longest match instead of the shortest match.

E.g.:
if (x = "hi")
 x = "string"
 return x

**Comment by akalicki** [comment] 2015-10-19 05:35
definitely needs to be changed for strings, anything else? comments are fine matching longest

**Comment by alexandramedway** [comment] 2015-10-19 14:19
This is probably because of the order in which we parse, not a bug in the scanner. Maybe we need to reorder the logic?

**Comment by alexandramedway** [comment] 2015-10-19 14:48
Also, could you explain the example you posted?

**Comment by akalicki** [comment] 2015-10-19 15:37
Nope this is because of the way the lexer matches via regex - it always
tries to match the longest possible string but for string literals we
really want it to match the shortest. There's a pretty easy way of
specifying that for a rule in the scanner I think!

On Oct 19, 2015, at 10:19 AM, Alexandra Medway <notifications@github.com>
wrote:

This is probably because of the order in which we parse, not a bug in the
scanner. Maybe we need to reorder the logic?

—
Reply to this email directly or view it on GitHub
<https://github.com/alexandramedway/plt/issues/2#issuecomment-149226429>.

**Comment by akalicki** [comment] 2015-10-19 15:39
In the example, our scanner will math from the first quotes to the ones
after 'string' as one token, whereas we want it to catch the two strings
individually.

On Oct 19, 2015, at 10:19 AM, Alexandra Medway <notifications@github.com>
wrote:

This is probably because of the order in which we parse, not a bug in the
scanner. Maybe we need to reorder the logic?

—
Reply to this email directly or view it on GitHub
<https://github.com/alexandramedway/plt/issues/2#issuecomment-149226429>.

**Comment by lillyfwang** [comment] 2015-10-19 15:54
The output of our scanner for the example is:

IF: if
LPAREN: (
ID: x
ASN: =
STRING_LITERAL: "hi") x = "string" ** Problem lies here **
RETURN: return
ID: x

**Comment by alexandramedway** [comment] 2015-10-19 16:02
Ok that makes sense. 

On another note, aren't we not allowing people to change variables once they are declared? Aka, variables are immutable? In which case the example you posted shouldn't compile, because you would be trying to reassign x to something else (whereas you would have to 'set x = "hello" ' if you want to have an 'x' corresponding to a 'hello'). This is a completely different discussion (and we still have the problem you initially posted, great catch!), but thought it was worth bringing up based on the example you posted.

**Comment by akalicki** [comment] 2015-10-19 16:20
Strings being immutable doesn't mean we can't reassign to the variable doesn't it? We're not actually changing "hi" in this example.

But this is dummy code, it's not supposed to work just is demonstrating that the scanner's not matching the right tokens.

**Comment by dannyech** [comment] 2015-10-19 18:56
I think I know why this is happening:

our string regex is this: `'"' ( ([^ '"'] | '\"')* as strlit) '"'`

We need the `'\"'` so that users can put the `"` character in strings delimited by `" "`. But in our actual regex I think we are escaping `"` itself by putting the `\` in front of it.

I think changing this part of the regex to possibly `'\\"'` or `'\\' _` might resolve the problem.

New regex: `'"' ( ([^ '"'] | '\\"')* as strlit) '"'` or `'"' ( ([^ '"'] | '\\' _ )* as strlit) '"'`

**I'm not going to make any changes yet because Alexandra added a new branch by accident and I'm unsure which branch to make the change to now.**

**Comment by dannyech** [comment] 2015-10-19 19:17
Re: the two options are actually `'"' ( ([^ '"'] | "\\\"")* as strlit) '"'` or `'"' ( ([^ '"'] | '\\' _ )* as strlit) '"'`

**Closed** 2015-10-19 22:14 UTC
Labels: bug, scanner
